---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Важно обеспечить быстрый отклик интерфейса при взаимодействии с пользователем.
  - Адаптивная верстка должна корректно отображаться на различных устройствах, включая мобильные телефоны, планшеты и настольные компьютеры.
  - Фильтрация товаров должна включать различные критерии, такие как цена, рейтинг, наличие скидок и другие параметры.
  - Корзина должна храниться в сессии браузера, чтобы пользователь мог продолжить покупки при случайном закрытии браузера.
  - Важно чтобы сайт верно отображал интерфейс как на английском так и на русском.
  - При подтверждении заказа пользователю нужно указать контакт для заказа.
  - При добавлении сразу нескольких товаров в корзину итоговая сумма заказа должна верно отображаться.
  - После выбора одной из категорий товаров можно снова выбрать все категории.
